{% set name = "bad_path" %}

# Read version from package __init__.py
{% set version = load_file_regex(load_file='bad_path/__init__.py', regex_pattern='__version__\s*=\s*["\']([^"\']+)["\']') %}

package:
  name: {{ name|lower }}
  version: {{ version[1] }}

source:
  path: ..
  
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.10

test:
  imports:
    - bad_path
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stonerlab/bad_path
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to identify potentially dangerous file paths
  description: |
    bad_path provides functions to test whether a supplied file path points to a
    system-sensitive location, taking into account different OS platforms.
  doc_url: https://stonerlab.github.io/bad_path/
  dev_url: https://github.com/stonerlab/bad_path

extra:
  recipe-maintainers:
    - gb119
